<?php if($this->messages): ?>
<?php foreach ($this->messages as $message): ?>
    <div class="alert alert-dimissible <?php echo $this->message_type ? $this->message_type : 'alert-info' ?>" >
    	<?php echo $message; ?>
    	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
    	  <span aria-hidden="true">&times;</span>
    	</button>		
    </div>
<?php endforeach; ?>
<?php endif; ?>