<?php if ($this->pageCount): ?>
<div class="paginationControl text-right">
<ul class="pagination small">
  <!-- Previous page link -->
  <?php if (isset($this->previous)): ?>
    <li>
      <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
        &lt;
      </a>
    </li>
  <?php else: ?>
    <li class="disabled" >
      <span>&lt;</span>
    </li>
  <?php endif; ?>
   
  <!-- Numbered page links -->
  <?php foreach ($this->pagesInRange as $page): ?>
    <?php if ($page != $this->current): ?>
      <li>
        <a href="<?php echo $this->url(array('page' => $page)); ?>">
          <?php echo $page; ?>
      </a>
      </li>
    <?php else: ?>
      <li class="active" >
          <span>
              <?php echo $page; ?>
          </span>
      </li>
    <?php endif; ?>
  <?php endforeach; ?>
   
  <!-- Next page link -->
  <?php if (isset($this->next)): ?>
    <li>
      <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
        &gt;
      </a>
    </li>
  <?php else: ?>
    <li class="disabled" >
      <span >&gt;</span>
    </li>
  <?php endif; ?>

</ul>
</div>
<?php endif; ?>