<script>
	(function($){
		$(document).ready(function(){		

			$('#fechar').click(function(e){
				e.preventDefault();
				window.location.href = '<?= $this->baseUrl() . '/'. $this->controllerName ?>';
			});			
		});
	})(jQuery);
</script>
<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-brand">
			<?= $this->barTitle; ?>
		</div>
		<div class="navbar-right" >			
			<a href="#" id="fechar" class="btn btn-primary navbar-btn" ><i class='glyphicon glyphicon-remove'></i> Fechar</a>
		</div>
	</div>
</div>