<div class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-brand">
			<i>Olá, <?= $this->user->nome; ?></i> 
		</div>	
		<div class="navbar-brand">
			|
		</div>	
		<ul class="nav navbar-nav">
        	<?php foreach ($this->menu[strtolower($this->user->role)] as $key => $name) : ?>
				
			<?php if($key == $this->controllerName .'/'. $this->actionName ) : ?>
				<li class="active" >
			<?php elseif($key == $this->controllerName AND $this->actionName == 'index') : ?>
				<li class="active" >
			<?php else: ?>
        		<li>
        	<?php endif; ?>
        			<a href="<?= $this->baseUrl() ?>/<?= $key ?>"><?= $name ?></a>
        		</li>
        	<?php endforeach; ?>
      	</ul>
		<div class="navbar-right" >
			<a title="Editar perfil" href="<?= $this->baseUrl() ?>/usuarios/user" id="edit-user" class="btn btn-link navbar-btn">
				<i class="glyphicon glyphicon-user" ></i>
			</a>  <a title="Sair" class="btn btn-link navbar-btn" href="<?= $this->baseUrl() ?>/login/logout">
				<i class="glyphicon glyphicon-off" ></i>
			</a>	
		</div>
	</div>
</div>