<?php 

$navs = array();
$navHtml = "";
$resources = explode(',', $this->user->resources);

foreach ($resources as $value){
	$value = explode(':', $value);
	if(!in_array($value[0], $navs)){
		$navs[] = $value[0];
		if($this->controllerName == $value[0]){
			$navHtml .="<li class='active'><a href='{$this->baseUrl()}/{$value[0]}'>{$value[0]}</a></li>";	
		}else{
			$navHtml .="<li><a href='{$this->baseUrl()}/{$value[0]}'>{$value[0]}</a></li>";	
		}		
	}
} 
?>	        		
<div class="navbar navbar-inverse">
	<div class="container">
		<div class="navbar-brand">
			<i>Olá, <?= $this->user->nome; ?></i> 
		</div>	
		<div class="navbar-brand">
			|
		</div>	
		<ul class="nav navbar-nav">
        	<?= $navHtml ?>
      	</ul>
		<div class="navbar-right" >
			<a title="Editar perfil" href="<?= $this->baseUrl() ?>/usuarios/user" id="edit-user" class="btn btn-link navbar-btn">
				<i class="glyphicon glyphicon-user" ></i>
			</a>  <a title="Sair" class="btn btn-link navbar-btn" href="<?= $this->baseUrl() ?>/login/logout">
				<i class="glyphicon glyphicon-off" ></i>
			</a>	
		</div>
	</div>
</div>