<div class="navbar navbar-default">
	<div class="container">
		<div class="navbar-brand">
			<?= $this->barTitle; ?>
		</div>	
		<div class="navbar-form navbar-left">
			<div class="form-group" >				
				<input type="text" id="search" class="form-control" placeholder="Pesquisar" />
			</div>			
		</div>
		<div class="navbar-right" >
			<a id="verlixeira" href="<?= $this->baseUrl() . '/' . $this->controllerName ?>/index/filter/0" class="btn btn-default navbar-btn">Ver lixeira</a>
			<a id="verarquivados" href="<?= $this->baseUrl() . '/' . $this->controllerName ?>/index/filter/3" class="btn btn-default navbar-btn">Itens Arquivados</a>
			<?php 
			     // Pemissão para exclusão do item
			     if($this->user->role != 'Corretor') : 
			 ?>			
			<a style="display: none;" href="#" id="remove" class="btn btn-danger navbar-btn" title="Remover definitivamente item(s) selecionados" ><i class="glyphicon glyphicon-remove-sign" ></i> Remover</a>
			<?php endif; ?>
			<a style="display: none;" href="#" id="restore" class="btn btn-success navbar-btn" title="Restaura item(s) selecionados" ><i class="glyphicon glyphicon-retweet" ></i> Restaurar</a>				
			<a href="#" id="lixeira" class="btn btn-danger navbar-btn" title="Enviar item(s) selecionados para Lixeira" ><i class="glyphicon glyphicon-trash" ></i> Lixeira</a>
			<a href="#" id="arquivados" class="btn btn-warning navbar-btn" title="Enviar item(s) selecionados para Arquivados" ><i class="glyphicon glyphicon-tasks" ></i> Arquivar</a>
			<a href="#" id="edit" class="btn btn-info navbar-btn" title="Editar item selecionado" ><i class="glyphicon glyphicon-edit" ></i> Editar</a>			
		</div>		
	</div>
</div>