<div class="container">
	<table class="table table-condensed table-hover table-striped" >
		<thead>
			<tr>
				<th>
					#id
				</th>
				<th>
					Nome
				</th>
				<th>
					E-mail
				</th>
				<th>
					Perfil
				</th>
				<th>
					Acesso
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->data as $key => $data) : ?>
				<tr>
					<td>
						<?php echo $data->id; ?>
					</td>
					<td>
						<a href="<?= $this->baseUrl() ?>/usuarios/edit/id/<?= $data->id ?>">
							<?php echo $data->nome; ?>
						</a>
					</td>
					<td>
						<?php echo $data->email; ?>
					</td>
					<td>
						<?php echo $data->role; ?>
					</td>
					<td>
						<?php echo $data->acesso; ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>