
<?= $this->render('common/top-bar-list.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
<form name="usuarios-list" id="usuarios" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>
					<th>Nome</th>
					<th>E-mail</th>
					<th>Perfil</th>
					<th class="text-center" >Ativo</th>	
				</tr>
			</thead>
			<tbody>	
				<?php foreach ($this->paginator as $key => $data) : ?>
					<tr>
					<td><input class="checkbox" id="<?= $data['id']; ?>" type="checkbox"
						name="<?= $data['id']; ?>"></td>
					<td>
						<a href="<?= $this->baseUrl() ?>/usuarios/edit/id/<?= $data['id'] ?>">
							<?= $data['nome']; ?>
						</a>
					</td>
					<td>
							<?= $data['email']; ?>
						</td>
					<td>
							<?= $data['role']; ?>
						</td>
					
							<?php if($data['acesso']) : ?>
					<td class="success text-center" >
								<i class="glyphicon glyphicon-ok-sign"></i>
							<?php else : ?>
					<td class="danger text-center" >
								<i class="glyphicon glyphicon-remove-sign"></i>
							<?php endif; ?>
						</td>					
				</tr>
				<?php endforeach; ?>
		</tbody>
		</table>
		<input type="hidden" name="search" value="<?= isset($this->data['search']) ? $this->data['search'] : '' ?>" >		
	</form>
	
	<?php if($this->paginator) : ?>
    	<?= $this->paginationControl($this->paginator, 'Sliding', 'common/pagination.phtml'); ?>	
    <?php endif; ?>
    
    <?php if(!$this->paginator) : ?>
    	<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
    <?php endif;?>
	
</div>


<?php //Pegando o script.js ?>
<?= $this->render('common/scripts-js/script-bar-list.phtml'); ?>
