<div class="navbar navbar-default">
    <div class="container">
    	<div class="navbar-brand">
    		<?= $this->barTitle; ?>
    	</div>
    	<div class="navbar-right" >
			<button id="submitFiles" class="btn btn-info navbar-btn">
				<i class="glyphicon glyphicon-upload"></i> Upload
			</button>
			<button id="addFileInput" class="btn btn-success navbar-btn">
				<i class="glyphicon glyphicon-plus"></i> Mais
			</button>
			<a href="<?= $this->baseUrl() .'/propostas/edit/id/'. $this->propostaId ?>" id="fechar" class="btn btn-primary navbar-btn" ><i class='glyphicon glyphicon-remove'></i> Fechar</a>
		</div>    	
    </div>
</div>
<div class="container panel panel-body panel-default">		
	<form id="ajaxUpload" class="form">
		<?php if(isset($this->propostaId)): ?>
		<?php //Passando id da proposta para incluir no nome do documento ?>
			<input type="hidden" value="<?= $this->propostaId; ?>" name="id" >	
		<?php endif; ?>
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon">
					<a href="#" title="Remover arquivo" ><i class="glyphicon glyphicon-remove"></i></a>
				</div>
				<input type="file" class="form-control" name="file-1" >
			</div>
		</div>
	</form>	
	<div id="listUploads">
		
	</div>	
</div>
<script>	
	var totalFileInput = 1,
	inputGroup = '<div class="form-group"><div class="input-group"><div class="input-group-addon"><a title="Remover arquivo" href="#" ><i class="glyphicon glyphicon-remove"></i></a></div><input type="file" class="form-control" name="file-'+totalFileInput+'" ></div></div>';
	
	$("#addFileInput").click(function(e){
		e.preventDefault();
		totalFileInput++;
		$("#ajaxUpload").append('<div class="form-group"><div class="input-group"><div class="input-group-addon"><a title="Remover arquivo" href="#" ><i class="glyphicon glyphicon-remove"></i></a></div><input type="file" class="form-control" name="file-'+totalFileInput+'" ></div></div>');
	});

	$('body').on('click','.input-group-addon a',function(e){
		e.preventDefault();
		$(this).parents('.form-group').remove();
	});

	$("#submitFiles").click(function(e){
		e.preventDefault();

		var formData = new FormData(document.getElementById('ajaxUpload'));

		$.ajax({
			method: 'Post',			
			data: formData,
			url: '<?= $this->baseUrl() ?>/documentos/upload-ajax',
			enctype: 'multipart/form-data',
			processData: false,
			contentType: false
		}).done(function(data){
			if(data.error){
				console.log('<p class="alert alert-error" >'+data.error+'</p>');
			}

			if(data){
				$("#listUploads").html(data);
				$('.form-group').remove();
				$("#ajaxUpload").append(inputGroup);
				
			}

			if(data == ""){
				$("#listUploads").html('<p class="alert alert-danger" >Problemas ao tentar fazer upload</p>');
			}
		})
	})
</script>