<div class="container">	
	<h3>Anexos</h3>
	<form id="ajaxUpload" class="form">		
		<div class="form-group">
			<div class="input-group">
				<div class="input-group-addon">
					<a href="#" title="Remover arquivo" ><i class="glyphicon glyphicon-remove"></i></a>
				</div>
				<input type="file" class="form-control" name="file-1" >
			</div>
		</div>
	</form>	
	<div>
		<div id="addFileInput" class="btn btn-success">
			<i class="glyphicon glyphicon-plus"></i> Mais
		</div>
		<div id="submitFiles" class="btn btn-info">
			<i class="glyphicon glyphicon-upload"></i> Upload
		</div>
	</div>
	<div id="listUploads">
		
	</div>
</div>
<script>	
	var totalFileInput = 1;
	$("#addFileInput").click(function(e){
		e.preventDefault();
		totalFileInput++;
		$("#ajaxUpload").append('<div class="form-group"><div class="input-group"><div class="input-group-addon"><a title="Remover arquivo" href="#" ><i class="glyphicon glyphicon-remove"></i></a></div><input type="file" class="form-control" name="file-'+totalFileInput+'" ></div></div>');
	});

	$('body').on('click','.input-group-addon a',function(e){
		e.preventDefault();
		$(this).parents('.form-group').remove();
	});

	$("#submitFiles").click(function(e){
		e.preventDefault();

		var formData = new FormData(document.getElementById('ajaxUpload'));

		$.ajax({
			method: 'Post',			
			data: formData,
			url: '<?= $this->baseUrl() ?>/documentos/upload-ajax',
			enctype: 'multipart/form-data',
			processData: false,
			contentType: false
		}).done(function(data){
			if(data.error){
				console.log(data.error)
			}

			if(data){
				$("#listUploads").html(data);
			}
		})
	})

</script>