<div class="navbar navbar-default">
    <div class="container">
    	<div class="navbar-brand">
    		<?= $this->barTitle; ?>
    	</div>
    	<div class="navbar-right" >
    		<a href="#" id="salvar" class="btn btn-info navbar-btn" > <i class='glyphicon glyphicon-ok' ></i> Salvar</a>
    		<a href="<?= $this->baseUrl() .'/propostas/edit/id/'. $this->id ?>" id="fechar" class="btn btn-primary navbar-btn" ><i class='glyphicon glyphicon-remove'></i> Fechar</a>
    	</div>
    </div>
</div>
<div class="container">
	<?= $this->render('common/message.phtml'); ?>
</div>
	
<?php if (!empty($this->form)) : ?>

<form class="container " id="<?= $this->form->getId(); ?>" method="<?= $this->form->getMethod(); ?>" enctype="<?= $this->form->getEnctype(); ?>">
		<div class="row" >
			<table class="table table-striped table-condensed table-bordered" >
    			<tr>
    				<td>
    					<label>
    						<?= $this->form->sinal->getLabel() ?>
    					</label>
    					<div class="input-group col-xs-4">    						
    						<span class="input-group-addon" >R$</span>
    						<input class="form-control" type="text" name="sinal" value="<?= $this->form->sinal->getValue() ?>" />
    					</div>    	
    					<?php if($this->form->sinal->getMessages()): ?>
    						<ul class="errors">
        					<?php foreach ($this->form->sinal->getMessages() AS $message) : ?>
        						<li><?= $message; ?></li>	
        					<?php endforeach;?>				         
    					</ul>
    					<?php endif;?>           	
                    	<?= $this->form->id_cliente ?>
    				</td>
    			</tr>
    			<tr>    				
    				<td>
    					<table class="table" >
    						<thead>
    							<tr>
    								<th>
        								VALOR
        							</th>
        							<th style="width: 15%" >
        								VENCIMENTO
        							</th>
        							<th style="width: 15%"  >
        								TIPO
        							</th>
        							<th >
        								<a id="add-parcelas" class="btn btn-default" >
        									<i class="glyphicon glyphicon-plus" ></i>
        								</a>
        							</th>    							
    							</tr>    							
    						</thead>
						<tbody id="lista-parcelas" >
    					<?php if($this->form->parcelas->getValue()): ?>
    						<?php 
    						     $parcelas = json_decode($this->form->parcelas->getValue(), true);    						      
    						  ?>     						  
    						  <tr>
    						  	<?= $this->form->parcelas ?>
    						  </tr>					
    						<?php foreach ($parcelas as $key => $parcela): ?>
    							<tr >
        							<td>        								
        								<div class="form-group" >
        									<div class="input-group">
            									<span class="input-group-addon" >R$</span>
            									<input class="form-control" type="text" name="parcelas[<?php echo $key; ?>][valor]" value="<?php echo $parcelas[$key]['valor'] ?>" />
            								</div>
        								</div>
        							</td>    							
        							<td>
        								<div class="form-group relative" >        									      								
	        								<input id="date-<?= $key;?>" class="form-control date" type="text" name="parcelas[<?php echo $key; ?>][vencimento]" value="<?php echo $parcelas[$key]['vencimento'] ?>" />
	        								<div class="input-group-addon" >
	        									<span class="glyphicon glyphicon-calendar"></span>
	        								</div>            								
        								</div>
        							</td>
        							<td>
        								<select class="form-control" name="parcelas[<?php echo $key; ?>][tipo]" >
    									<?php foreach ($this->selectOptions as $key => $option) : ?>
    										<option value="<?= $key; ?>" ><?= $option ?></option>
    									<?php endforeach;?>
        								</select>
        							</td>  
									<td>
										<button class="remove-parcela btn btn-danger" >
        									<i class="glyphicon glyphicon-minus" ></i>
        								</button>
									</td> 							
        						</tr>
    						<?php endforeach; ?>
    					<?php else: ?>
    						<tr>
    							<td>
    								<div class="form-group" >
    									<div class="input-group">
        									<span class="input-group-addon" >R$</span>
        									<input class="form-control" type="text" name="parcelas[0][valor]" />
        								</div>
    								</div>
    							</td>    							
    							<td>
    								<div class="form-group relative" >    									
    									<input id="date-0" class="form-control date" type="text" name="parcelas[0][vencimento]" />
										<div class="input-group-addon" >
											<span class="glyphicon glyphicon-calendar"></span> 
										</div>        								
    								</div>
    							</td>
    							<td>
    								<select class="form-control" name="parcelas[0][tipo]" >
    								<?php foreach ($this->selectOptions as $key => $option) : ?>
    										<option value="<?= $key; ?>" ><?= $option ?></option>
									<?php endforeach;?>
    								</select>
    							</td>  
    							<td>
									<button class="remove-parcela btn btn-danger" >
    									<i class="glyphicon glyphicon-minus" ></i>
    								</button>
								</td> 							
    						</tr>
						</tbody>
    					<?php endif;?>
    					</table>
    				</td>
    			</tr>	
    		</table>
		</div>
		<?= $this->form->enviar; ?>
	</form>
<?php endif; ?>	
	<script>
    	$("input[id^=date").datetimepicker({
    		format: 'DD/MM/YYYY'
    	});    	
    	
		var totalParcelas = $("#lista-parcelas tr").length - 1;		
		$("#add-parcelas").click(function(e){
			e.preventDefault();
            totalParcelas++;
            var tr = '<tr>';
            tr +='<td>';
            tr +='<div class="form-group" >';
            tr +='<div class="input-group">';
            tr +='<span class="input-group-addon" >R$</span>';
            tr +='<input class="form-control" type="text" name="parcelas['+ totalParcelas +'][valor]" value="" />';
            tr +='</div>';
            tr +='</div>';
            tr +='</td>';
            tr +='<td>';
            tr +='<div class="form-group relative" >';            
            tr +='<input id="date-'+ totalParcelas +'" class="form-control" type="text" name="parcelas['+ totalParcelas +'][vencimento]" value="" />';
            tr +='<div class="input-group-addon" >';
            tr +='<span class="glyphicon glyphicon-calendar"></span>';
            tr +='</div>';            
            tr +='</div>';
            tr +='</td>';
            tr +='<td>';
            tr +='<select class="form-control" name="parcelas['+ totalParcelas +'][tipo]" >';
            <?php foreach ($this->selectOptions as $key => $option) : ?>
    			tr +='<option value="<?= $key; ?>" ><?= $option ?></option>';
    		<?php endforeach;?>
            tr +='</select>';
            tr +='</td>';
            tr +='<td>';
            tr +='<a class="remove-parcela btn btn-danger" >';
            tr +='<i class="glyphicon glyphicon-minus" ></i>';
            tr +='</a>';
            tr +='</td>';
            tr +='</tr>';			
            $('#lista-parcelas').append(tr);

            // Adicionando o date
            $("input[id^=date").datetimepicker({
        		format: 'DD/MM/YYYY'
        	});  
            
		});		
	
		$('body').on('click','.remove-parcela', function(e){
			e.preventDefault();
			var self = $(this);
			if(totalParcelas-1){
				bootbox.confirm("Remover parcela?", function(result){
					if(result){
						self.parent().parent().remove();
						totalParcelas--;
					}
				});
			}else{
				bootbox.alert('Operação não permitida!!');
			}
		});
<?php if (!empty($this->form)) : ?>
		$("#salvar").click(function(e){
			e.preventDefault();
			$('#<?= $this->form->getId(); ?>').submit();
		});
<?php endif; ?>		
		
	</script>