<?= $this->render('common/top-bar-edit.phtml')?>
<div class="container">
	<?= $this->render('common/message.phtml'); ?>	
</div>
<?php if (!$this->hide) : ?>
<div class="container">	
	<div class="panel panel-body panel-default" >	
    	<form class="<?= $this->form->getAttrib('class'); ?>" name="<?= $this->form->getAttrib('name'); ?>" action="<?= $this->form->getAction() ?>" method="<?= $this->form->getMethod() ?>" enctype="<?= $this->form->getEnctype() ?>" >
    		<?php foreach ($this->form->getElements() as $element){
    		    
    		    if(isset($this->data['status']) && $this->data['status'] == 1 &&  'Zend_Form_Element_Hidden' != $element->getType()){
    		        echo $element->setAttrib('disabled', 'disabled');
    		    }else{
    		        echo $element;
    		    }
    	             
           } ?>	
    	</form>		
	</div>
			
	<?php if($this->parcelas) :?>		
		<h3>Parcelas</h3>
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>#</th>
					<th>Valor</th>
					<th>Vencimento da parcela</th>
					<th>Tipo</th>
				</tr>
			</thead>			
			<tbody>
			<?php foreach ($this->parcelas as $key => $parcela): ?>
				<tr>
					<td><?php echo $key+1 ?>ª</td>
					<td><?php echo $parcela['valor'] ?></td>
					<td><?php echo $parcela['vencimento'] ?></td>
					<td><?php echo $parcela['tipo'] ?></td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>
	<?php endif;?>
	<?php if(isset($this->data['status']) && $this->data['status'] != 1) : ?>
	<p>
		<a href="<?= $this->baseUrl(). '/propostas/condicoes-pagamento/id/'. $this->form->id->getValue(); ?>" class="btn btn-info">Adcionar Condições de pagamento</a>
	</p> 
	<?php endif; ?>
	<?php if($this->anexos) :?>
	<h3>Anexos</h3>
	<table class='table table-striped table-hover table-condensed'>
		<thead>
			<tr>
				<th>Nome</th>
				<th>Tamanho</th>
				<th class="text-center">Extensão</th>
				<th>Modificado</th>
				<th class="text-center">Remover</th>
			</tr>
		</thead>
		<tbody>
		<?php foreach ($this->anexos as $file) : ?>		
			<tr>
				<td><a target="_blank" class="btn btn-link"
					href="<?= $this->baseUrl() .'uploads/' . $file['name']; ?>"> <?= $file['name']; ?>
				</a></td>
				<td><?= $this->documentos->formatSizeUnits($file['size']); ?>
				</td>
				<td class="text-center"><?= $file['extension']; ?>
				</td>
				<td><?= date('d/m/Y H:i:s', $file['date'])?>
				</td>
				<td class="text-center"><a class="btn btn-danger removefile"
					href="<?= $file['name'] ?>"> <i class="glyphicon glyphicon-remove"></i>
				</a></td>
			</tr>		
		<?php endforeach; ?>
		</tbody>
	</table>
	<?php endif; ?>
	<?php if(isset($this->data['status']) && $this->data['status'] != 1) : ?>
	<p>
		<a href="<?= $this->baseUrl(). '/propostas/anexos/id/'. $this->form->id->getValue(); ?>" class="btn btn-info">Adicionar anexos</a>
	</p>
	<?php endif; ?>	
	
	<?php if(!isset($this->data['status'])) : ?>
		<p class="alert alert-info" ><i>Para anexar documentos e/ou adicionar forma de pagamento é necessário salvar a proposta antes.</i></p>
	<?php endif; ?>
	
</div>

<script>
	$("#data_nasc, #conj_data_nasc").datetimepicker({
		format: 'DD/MM/YYYY'
	});	

	if(document.getElementById('conj_estado')){
		new dgCidadesEstados({
	        cidade: document.getElementById('conj_cidade'),
	        estado: document.getElementById('conj_estado'),
	        estadoVal: '<?= $this->form->conj_estado->getValue(); ?>',		    	
        	cidadeVal: '<?= $this->form->conj_cidade->getValue(); ?>'		        
      	});	
	}	

	if(document.getElementById('naturalidade_estado')){
		new dgCidadesEstados({
	        cidade: document.getElementById('naturalidade'),
	        estado: document.getElementById('naturalidade_estado'),
	        estadoVal: '<?= $this->form->naturalidade_estado->getValue(); ?>',		    	
        	cidadeVal: '<?= $this->form->naturalidade->getValue(); ?>'		        
      	});	
	}

	if(document.getElementById('conj_naturalidade_estado')){
		new dgCidadesEstados({
			cidade: document.getElementById('conj_naturalidade'),		        
	        estado: document.getElementById('conj_naturalidade_estado'),
	        estadoVal: '<?= $this->form->conj_naturalidade_estado->getValue(); ?>',		    	
        	cidadeVal: '<?= $this->form->conj_naturalidade->getValue(); ?>'		        		        
      	});	
	}

	$(".removefile").click(function(e){		
		e.preventDefault();
		var self = this;
		
		var file = $(this).attr('href');
		bootbox.confirm('Remover o arquivo: ' + file + '?',function(result){

			var formdata = new FormData();
			formdata.append("names", file);			
			
			if(result){
				$.ajax({
					type: 'POST',
					url:'<?= $this->baseUrl() . '/documentos/remove-files' ?>',
					data: formdata,
					processData: false,
					contentType: false,
				}).success(function(data, textStatus){
					var data = JSON.parse(data);
					if(data[0].removed){
						$(self).parents('tr').remove();
					}
				});
			}
		});
	});
	
	var id_imovel = '<?= $this->form->imovel->getValue(); ?>',
		blocos,
		unidades;


	if(id_imovel){		
		var formdata = new FormData();
		formdata.append("id", id_imovel);
		// Solicitando que o resultado seja so das unidades;
		formdata.append("unidades", true);	
		
		$.ajax({
			type: 'POST',
			url:'<?= $this->baseUrl() . '/empreendimentos/get-imovel' ?>',
			data: formdata,
			processData: false,
			contentType: false,
		}).success(function(data){
			var data = JSON.parse(data);			
			setDataImovel(data, function(){				
				$('#imovel_bloco_quadra option').remove();
				$('#imovel_bloco_quadra').append('<option value="0">-- Selecione -- </option>');
				
				$.each(blocos, function(i,bloco){
					if(bloco == '<?= $this->form->imovel_bloco_quadra->getValue(); ?>'){
						$('#imovel_bloco_quadra').append('<option value="'+ bloco +'" selected="selected" >'+ bloco +'</option>');
					}else{
						$('#imovel_bloco_quadra').append('<option value="'+ bloco +'" >'+ bloco +'</option>');
					}					
				});	
				
			});					
			
		});
	}

	$("#imovel").change(function(e){
		
		var id = $(this).val();
		var formdata = new FormData();

		if(id != 0){
			
			formdata.append("id", id);
			// Solicitando que o resultado seja so das unidades;
			formdata.append("unidades", true);	
			
			$.ajax({
				type: 'POST',
				url:'<?= $this->baseUrl() . '/empreendimentos/get-imovel' ?>',
				data: formdata,
				processData: false,
				contentType: false,
			}).success(function(data, textStatus){			
				var data = JSON.parse(data);
				
				setDataImovel(data);

				$('#imovel_bloco_quadra option').remove();
				$('#imovel_bloco_quadra').append('<option value="0">-- Selecione -- </option>');
				
				$.each(blocos, function(i,bloco){
					$('#imovel_bloco_quadra').append('<option value="'+ bloco +'" >'+ bloco +'</option>');
				});			
			});
		}else{
			$('#imovel_bloco_quadra option').remove();
			$('#imovel_bloco_quadra').append('<option value="0">-- Selecione -- </option>');			
		}
		
	});

	var setDataImovel = function(data, callback){		
		blocos = [];
		unidades = [];		
		for (var i = 0, total = data.length; i < total; i++) {
			if(blocos.indexOf(data[i]['bloco-quadra']) == -1){
				blocos.push(data[i]['bloco-quadra']);
				unidades[data[i]['bloco-quadra']] = new Array();
			}
			unidades[data[i]['bloco-quadra']].push(data[i].unidade);
		};

		if(callback){
			callback();
		}
	}
		
</script>

<?php endif; ?>