
<?= $this->render('common/top-bar-list-sample.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
<form name="propostas-list" id="propostas" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>
					<th>Nome</th>
					<th>CPF</th>
					<th>Data de criação</th>
					<th>Criado</th>
					<th>Modificado</th>
					<th>Status</th>
					<th title="Autorizar pagamento?">Autorizado</th>
				</tr>
			</thead>
			<tbody>			
				<?php if($this->data) : ?>			
				<?php foreach ($this->data as $key => $data) : ?>
					<tr>
					<td><input class="checkbox" id="<?= $data->id; ?>" type="checkbox"
						name="<?= $data->id; ?>"></td>
					<td>
						
						<?php if($data->locked == 1): ?>
							 <i title="Sendo editado por: <?= $this->model_user->selectNameById($data->locked_by) ?> " class="glyphicon glyphicon-lock"></i>
						<?php endif; ?>

						<a href="<?= $this->baseUrl() ?>/<?= $this->controllerName; ?>/edit/id/<?= $data->id ?>">
							<?= $data->nome; ?>
						</a>
					</td>
					<td>
						<?= $data->cpf; ?>
					</td>
					<td>
						<?php $create = new Zend_Date($data->data); echo $create->toString('d/M/Y'); ?>
					</td>					
					<td>
						<?= $this->model_user->selectNameById($data->created_user_id); ?>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data->last_user_id); ?>
					</td>					
					<td>
						<?php if(in_array(CURRENT_USER_ROLE, array('Administrador','Diretor','Gerente'))) : ?>
							<select rel="<?= $data->id; ?>" class="form-control status" >
								<option value="1" <?php if($data->status == '1') echo "Selected='Selected'" ?> >Aprovado</option>
								<option value="2" <?php if($data->status == '2') echo "Selected='Selected'" ?> >Aguardando</option>
								<option value="3" <?php if($data->status == '3') echo "Selected='Selected'" ?> >Negado</option>
								<option value="4" <?php if($data->status == '4') echo "Selected='Selected'" ?> >Incompleto</option>
							</select>
						<?php else : ?>
							<?php if($data->status == 1): ?>
								Aprovado
							<?php elseif($data->status == 2): ?>
								Aguardando
							<?php elseif($data->status == 3): ?>
								Negado
							<?php else: ?>
								Incompleto
							<?php endif; ?>
						<?php endif; ?>
					</td>
					<td>
						<?php if(in_array(CURRENT_USER_ROLE, array('Administrador','Diretor'))) : ?>
							<select <?php if(in_array($data->status, array('2','3'))) echo 'disabled' ?> rel="<?= $data->id; ?>" class="form-control autorizado" >
								<option value="0" <?php if($data->autorizado == '0') echo "Selected='Selected'" ?> >Não</option>
								<option value="1" <?php if($data->autorizado == '1') echo "Selected='Selected'" ?> >Sim</option>
							</select>
							<?php else: ?>
							<?= $data->autorizado ? 'Sim' : 'Não' ; ?>
						<?php endif; ?>
					</td>
				</tr>
				<?php endforeach; ?>
				<?php endif; ?>
		</tbody>
		</table>		
	</form>
	
	<?php if(!$this->data) : ?>
		<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
	<?php endif;?>
	
</div>
<?php if(in_array(CURRENT_USER_ROLE, array('Administrador','Diretor','Gerente'))) : ?>
<script type="text/javascript">
	var statusBefore;
	$('.status').on('focus',function(){
		statusBefore = $(this).val();
	}).change(function(e){
		var self = $(this);		
		bootbox.confirm('Alterar status da proposta?',function(result){
			if(result){				
				var formdata = new FormData(),
					id = self.attr('rel');

				if(self.val() == '2' || self.val() == '3'){
					$('.autorizado[rel='+id+']').val('0');
					$('.autorizado[rel='+id+']').attr('disabled','');					
		    	}else{
		    		$('.autorizado[rel='+id+']').removeAttr('disabled');
		    	}
		    	
    			formdata.append('id', id);
    			formdata.append('status', self.val());
    			formdata.append('autorizado', $('.autorizado[rel='+id+']').val());
    			formdata.append('last_user_id', '<?= CURRENT_USER_ID; ?>');
    			
    			$.ajax({
    				type: 'POST',
    				url:'<?= $this->baseUrl() . '/' . $this->controllerName .'/altera-state' ?>',
    				data: formdata,
    				processData: false,
    				contentType: false,
    			}).success(function(data){
    				if(data){
        				console.log('alterado com sucesso');
        			}
    			});    			
			}else{
				self.val(statusBefore);						
			}			
		});
    	
	});
	
</script>
<?php endif; ?>

<?php if(in_array(CURRENT_USER_ROLE, array('Administrador','Diretor'))) : ?>
<script type="text/javascript">
	var autorizadoBefore;
	$('.autorizado').on('focus',function(){
		autorizadoBefore = $(this).val();
	}).change(function(e){
		var self = $(this);		
		bootbox.confirm('Mudar autorização da proposta?',function(result){
			if(result){
				var formdata = new FormData(),
				id = self.attr('rel');
								
    			formdata.append('id', id);
    			formdata.append('autorizado', self.val());
    			formdata.append('last_user_id', '<?= CURRENT_USER_ID; ?>');
    			
    			$.ajax({
    				type: 'POST',
    				url:'<?= $this->baseUrl() . '/' . $this->controllerName .'/altera-state' ?>',
    				data: formdata,
    				processData: false,
    				contentType: false,
    			}).success(function(data){
        			if(data){
        				console.log('alterado com sucesso');
        			}
    				
    			});    			
			}else{
				self.val(statusBefore);						
			}			
		});
	});
	
</script>
<?php endif; ?>


