
<?= $this->render('common/top-bar-list-sample.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
<form name="propostas-list" id="propostas" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>					
					<th>Nome</th>
					<th>Criado</th>
					<th>Alterado</th>
					<th>Status</th>	
				</tr>
			</thead>
			<tbody>
				<?php if($this->data) : ?>			
				<?php foreach ($this->data as $key => $data) : ?>
					<tr>
					<td><input class="checkbox" id="<?= $data->id; ?>" type="checkbox"
						name="<?= $data->id; ?>"></td>
					<td>
						
						<?php if($data->locked == 1): ?>
							 <i title="Sendo editado por: <?= $this->model_user->selectNameById($data->locked_by) ?> " class="glyphicon glyphicon-lock"></i>
						<?php endif; ?>

						<a href="<?= $this->baseUrl() ?>/<?= $this->controllerName; ?>/edit/id/<?= $data->id ?>">
							<?= $data->nome; ?> / <?= isset($data->conj_nome); ?>
						</a>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data->created_user_id); ?>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data->last_user_id); ?>
					</td>					
					<td>
							<?php if($data->status == 1): ?>
								Aprovado
							<?php elseif($data->status == 2): ?>
								Aguardando
							<?php elseif($data->status == 3): ?>
								Negado
							<?php else: ?>
								Incompleto
							<?php endif; ?>
					</td>
				</tr>
				<?php endforeach; ?>
				<?php endif; ?>
		</tbody>
		</table>		
	</form>
	
	<?php if(!$this->data) : ?>
		<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
	<?php endif;?>
	
</div>