
<?= $this->render('common/top-bar-list-sample.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
<form name="propostas-list" id="propostas" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>					
					<th>Nome</th>
					<th>CPF</th>
					<th>Criado</th>
					<th>Alterado</th>
					<th>Status</th>	
				</tr>
			</thead>
			<tbody>			
				<?php if($this->data) : ?>			
				<?php foreach ($this->data as $key => $data) : ?>
					<tr>
					<td><input class="checkbox" id="<?= $data->id; ?>" type="checkbox"
						name="<?= $data->id; ?>"></td>
					<td>
						
						<?php if($data->locked == 1): ?>
							 <i title="Sendo editado por: <?= $this->model_user->selectNameById($data->locked_by) ?> " class="glyphicon glyphicon-lock"></i>
						<?php endif; ?>

						<a href="<?= $this->baseUrl() ?>/<?= $this->controllerName; ?>/edit/id/<?= $data->id ?>">
							<?= $data->nome; ?>
						</a>
					</td>
					<td>
						<?= $data->cpf; ?>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data->created_user_id); ?>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data->last_user_id); ?>
					</td>					
					<td>
						<?php if(in_array(CURRENT_USER_ROLE, array('Administrador','Diretor','Gerente'))) : ?>
							<select rel="<?= $data->id; ?>" class="form-control status" >
								<option value="1" <?php if($data->status == '1') echo "Selected='Selected'" ?> >Aprovado</option>
								<option value="2" <?php if($data->status == '2') echo "Selected='Selected'" ?> >Aguardando</option>
								<option value="3" <?php if($data->status == '3') echo "Selected='Selected'" ?> >Negado</option>
								<option value="4" <?php if($data->status == '4') echo "Selected='Selected'" ?> >Incompleto</option>
							</select>
						<?php else : ?>
							<?php if($data->status == 1): ?>
								Aprovado
							<?php elseif($data->status == 2): ?>
								Aguardando
							<?php elseif($data->status == 3): ?>
								Negado
							<?php else: ?>
								Incompleto
							<?php endif; ?>
						<?php endif; ?>
					</td>
				</tr>
				<?php endforeach; ?>
				<?php endif; ?>
		</tbody>
		</table>		
	</form>
	
	<?php if(!$this->data) : ?>
		<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
	<?php endif;?>
	
</div>
<script type="text/javascript">
	$('.status').blur(function(){		
		var formdata = new FormData(),
			id = $(this).attr('rel');
		formdata.append('id', id);
		formdata.append('status', $(this).val());
		formdata.append('last_user_id', '<?= CURRENT_USER_ID; ?>');
		// Solicitando que o resultado seja so das unidades;
		formdata.append("unidades", true);	
		
		$.ajax({
			type: 'POST',
			url:'<?= $this->baseUrl() . '/' . $this->controllerName .'/altera-state' ?>',
			data: formdata,
			processData: false,
			contentType: false,
		}).success(function(data){
			console.log(data);
		});
	});
	
</script>


