<div id="box-login" class="container">
	<div id="login">
		<?php if($this->logourl): ?>
			<p>
				<img alt="<?php echo $this->company_name; ?>" src="<?php echo $this->logourl ?>">
			</p>			
		<?php endif; ?>
		<?php if($this->messages): ?>
		<?php foreach ($this->messages as $message): ?>
		<div class="alert alert-dimissible alert-danger" >
			<?php echo $message; ?>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			  <span aria-hidden="true">&times;</span>
			</button>		
		</div>
		<?php endforeach; ?>
	<?php endif;?>
	<?php echo $this->form; ?>
	</div>
</div>
<div id="copy-login" class="fix-bottom">
	&copy; <?php echo date('Y') . ' - ' . $this->company_name; ?>
</div>