<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="pt-br" >
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<?= $this->headTitle(); ?>
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/bootstrap.min.css">	
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/bootstrap-theme.min.css">	
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/app.min.css">
	<script src="<?= $this->baseUrl() . "/"; ?>js/jquery.min.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/bootstrap.min.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/bootbox.min.js" ></script>
</head>
<body>	
	<?= $this->layout()->content; ?>	
</body>	
</html>
