<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="pt-br" >
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<?= $this->headTitle(); ?>
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/bootstrap.min.css">	
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/bootstrap-theme.min.css">	
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/bootstrap-datetimepicker.min.css">
	<link rel="stylesheet" href="<?php echo $this->baseUrl() . "/"; ?>css/app.min.css">
	<script src="<?= $this->baseUrl() . "/"; ?>js/moment.min.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/locale/pt-br.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/jquery.min.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/bootstrap.min.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/bootstrap-datetimepicker.min.js" ></script>	
	<script src="<?= $this->baseUrl() . "/"; ?>js/bootbox.min.js" ></script>
	<script src="<?= $this->baseUrl() . "/"; ?>js/cidades-estados-1.4-utf8.js" ></script>
</head>
<body>	
	<?= $this->render('common/top-menu.phtml'); ?>
	<?= $this->layout()->content; ?>
	<script>

		if(document.getElementById('estado')){
			new dgCidadesEstados({
		        cidade: document.getElementById('cidade'),
		        estado: document.getElementById('estado'),
		        estadoVal: 'GO',
	        	cidadeVal: 'Goiânia'
	      	});	
		}	

		if(document.getElementById('conj_estado')){
			new dgCidadesEstados({
		        cidade: document.getElementById('conj_cidade'),
		        estado: document.getElementById('conj_estado'),
		        estadoVal: 'GO',
	        	cidadeVal: 'Goiânia'
	      	});	
		}	


		$('#cep').on('blur', function(){
			
			val = $(this).val(),
			cep = val.replace(/[^\d]/, '');

			$.ajax({
				'method' : 'GET',
				'url' : 'http://cep.correiocontrol.com.br/' + cep +'.json'
			}).done(function(data){
				if(!data.error){
					$('#bairro').val(data.bairro);

					$('input#endereco').val(data.logradouro);
					$('input#cidade').val(data.cidade);
					$('input#estado').val(data.estado);

					$('select#cidade option[value='+ data.cidade +']').prop('selected', true);
					$('select#endereco option[value='+ data.estado +']').prop('selected', true);
				}				
			});

		});

		$('#conj_cep').on('blur', function(){
			
			val = $(this).val(),
			cep = val.replace(/[^\d]/, '');

			$.ajax({
				'method' : 'GET',
				'url' : 'http://cep.correiocontrol.com.br/' + cep +	'.json'
			}).done(function(data){
				if(!data.error){
					$('#conj_bairro').val(data.bairro);

					$('input#conj_endereco').val(data.logradouro);
					$('input#conj_cidade').val(data.cidade);
					$('input#conj_estado').val(data.estado);

					$('select#conj_cidade option[value='+ data.cidade +']').prop('selected', true);
					$('select#conj_endereco option[value='+ data.estado +']').prop('selected', true);
				}				
			});

		});

		$(document).on("keypress", ":input:not(textarea)", function(event) {
		    return event.keyCode != 13;
		});

	</script>
</body>	
</html>
