<?= $this->render('common/top-bar-list.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
	<form name="clientes-list" id="clientes" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>
					<th>Nome</th>
					<th>CPF</th>
					<th>Data do cadastro</th>
					<th>Criado</th>
					<th>Modificado</th>
					<th class="text-center" >Criar proposta</th>
				</tr>
			</thead>
			<tbody>
				<?php if($this->paginator) : ?>			
				<?php foreach ($this->paginator as $key => $data) :
				    $data = array_merge($data, json_decode($data['dados_cliente'], true));
				?>
					<tr>
					<td><input class="checkbox" id="<?= $data['id']; ?>" type="checkbox"
						name="<?= $data['id']; ?>"></td>
					<td>						
						<?php if($data['locked'] == 1): ?>
							 <i title="Sendo editado por: <?= $this->model_user->selectNameById($data['locked_by']) ?> " class="glyphicon glyphicon-lock"></i>
						<?php endif; ?>

						<a href="<?= $this->baseUrl() ?>/<?= $this->controllerName; ?>/edit/id/<?= $data['id']; ?>">
							<?= $data['nome']; ?>
						</a>
					</td>
					<td>
						<?= $data['cpf']; ?>
					</td>
					<td>
						<?php $this->date->set($data['data']);?>
						<?= $this->date->get('dd/MM/YYYY') ?>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data['created_user_id']); ?>
					</td>
					<td>
						<?= $this->model_user->selectNameById($data['last_user_id']); ?>
					</td>
					<td class="text-center" >
						<a title="Criar uma nova proposta para: <?= $data['nome']; ?>" class="btn btn-info" href="<?= $this->baseUrl()?>/propostas/edit/id/0/cid/<?= $data['id']; ?>" >
							<i class="glyphicon glyphicon-info-sign" ></i>
						</a>
					</td>				
				</tr>
				<?php endforeach; ?>
				<?php endif; ?>
		</tbody>
		</table>			
	</form>
	
	<?php if($this->paginator) : ?>
		<?= $this->paginationControl($this->paginator, 'Sliding', 'common/pagination.phtml'); ?>	
	<?php endif; ?>
	
	<?php if(!$this->paginator) : ?>
		<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
	<?php endif;?>
	
</div>
