<?= $this->render('common/top-menu.phtml'); ?>
<?= $this->render('common/top-bar-list.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
<form name="clientes-list" id="clientes" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>
					<th>Nome</th>
					<th>E-mail</th>
					<th>CPF</th>
					<th>Data do cadastro</th>					
				</tr>
			</thead>
			<tbody>
				<?php if($this->data) : ?>			
				<?php foreach ($this->data as $key => $data) : ?>
					<tr>
					<td><input class="checkbox" id="<?= $data->id; ?>" type="checkbox"
						name="<?= $data->id; ?>"></td>
					<td>
						<a href="<?= $this->baseUrl() ?>/clientes/edit/id/<?= $data->id ?>">
							<?= $data->nome; ?>
						</a>
					</td>
					<td>
							<?= $data->email; ?>
						</td>
					<td>
							<?= $data->cpf; ?>
						</td>					
							<?php 
							     $data1 = date_create($data->data); 
							     $data2 = date_create(Zend_Date::now()->toString('YYYY-MM-dd'));
							?>
							<?php if(date_diff($data1,$data2)->format('%a') <= '7'): ?>
					<td class="success text-center" >
								<?php $this->date->set($data->data);?>
								<?= $this->date->get('dd/MM/YYYY') ?>								
							<?php else : ?>
					<td class="danger text-center" >
								<?php $this->date->set($data->data);?>
								<?= $this->date->get('dd/MM/YYYY') ?>
							<?php endif; ?>
						</td>					
				</tr>
				<?php endforeach; ?>
				<?php endif; ?>
		</tbody>
		</table>		
	</form>
	
	<?php if(!$this->data) : ?>
		<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
	<?php endif;?>
	
</div>